"""The actions of the views of the entries, implemented by the main window."""

from pathlib import Path
from typing import Protocol

from models.transcript_segment import TranscriptSegment
from utils.env_keys import EnvKeys


class TranscriptDelegate(Protocol):
    def rename_entry_dialog(self, entry_id: str) -> None: ...
    def edit_note(self, entry_id: str) -> None: ...
    def edit_tag(self, entry_id: str) -> None: ...
    def reveal_entry(self, entry_id: str) -> None: ...
    def open_folder(self, folder: Path) -> None: ...
    def retry_entry(self, entry_id: str) -> None: ...
    def delete_entry(self, entry_id: str) -> None: ...
    def save_text(self, entry_id: str, text: str) -> None: ...
    def update_transcript(
        self, entry_id: str, segments: list[TranscriptSegment], text: str
    ) -> None: ...
    def summarize_entry(self, entry_id: str) -> None: ...
    def is_summarizing(self, entry_id: str) -> bool: ...
    def get_summary_error(self, entry_id: str) -> str: ...
    def translate_entry(
        self, entry_id: str, language: str, provider: str, model: str = ""
    ) -> None: ...
    def is_translating(self, entry_id: str) -> bool: ...
    def get_translation_error(self, entry_id: str) -> str: ...
    def save_translation_text(self, entry_id: str, text: str) -> None: ...
    def update_translation(
        self, entry_id: str, segments: tuple[str, ...], text: str
    ) -> None: ...
    def remove_translation(self, entry_id: str) -> None: ...
    def show_preferences(self, tab: str | None = None) -> None: ...
    def set_api_key(self, env_key: EnvKeys) -> None: ...
    def show_status(self, message: str, is_error: bool = False) -> None: ...


class EntryDelegate(TranscriptDelegate, Protocol):
    def cancel_entry(self, entry_id: str) -> None: ...
    def go_back_to_settings(self, entry_id: str) -> None: ...
    def select_entry(self, entry_id: str) -> None: ...
    def get_progress_message(self, entry_id: str) -> tuple[str, float | None]: ...
    def get_queue_position(self, entry_id: str) -> int | None: ...
