"""
The actions of the views of the entries (and of the list of the history). The
ones that only change the data are done by the controllers, which satisfy these
Protocols, while the ones that ask the user first or change what's shown are
done by the window.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Protocol

from models.transcript_segment import TranscriptSegment
from utils.env_keys import EnvKeys


class EntryFiles(Protocol):
    """Shows the files of the entries in the file manager."""

    def reveal_entry(self, entry_id: str) -> None: ...
    def open_folder(self, folder: Path) -> None: ...


class TranscriptEditor(Protocol):
    """Corrects, summarizes and translates the transcription of an entry."""

    def save_text(self, entry_id: str, text: str) -> None: ...
    def update_transcript(
        self, entry_id: str, segments: list[TranscriptSegment], text: str
    ) -> None: ...
    def summarize_entry(self, entry_id: str) -> None: ...
    def is_summarizing(self, entry_id: str) -> bool: ...
    def get_summary_error(self, entry_id: str) -> str: ...
    def translate_entry(
        self, entry_id: str, language: str, provider: str, model: str = ""
    ) -> None: ...
    def start_manual_translation(self, entry_id: str, language: str) -> None: ...
    def is_translating(self, entry_id: str) -> bool: ...
    def get_translation_error(self, entry_id: str) -> str: ...
    def save_translation_text(self, entry_id: str, text: str) -> None: ...
    def update_translation(
        self, entry_id: str, segments: list[TranscriptSegment], text: str
    ) -> None: ...
    def remove_translation(self, entry_id: str) -> None: ...


class JobControls(Protocol):
    """Transcribes an entry again or cancels it, and tells how it's going."""

    def retry_entry(self, entry_id: str) -> None: ...
    def cancel_entry(self, entry_id: str) -> None: ...
    def get_progress(self, entry_id: str) -> float | None: ...
    def get_progress_message(self, entry_id: str) -> tuple[str, float | None]: ...
    def get_queue_position(self, entry_id: str) -> int | None: ...


class EntryPrompts(Protocol):
    """The actions on an entry that ask the user for a value or a confirmation."""

    def ask_to_rename_entry(self, entry_id: str) -> None: ...
    def ask_for_note(self, entry_id: str) -> None: ...
    def confirm_delete_note(self, entry_id: str) -> None: ...
    def ask_for_tag(self, entry_id: str) -> None: ...
    def confirm_delete_entry(self, entry_id: str) -> None: ...


class Navigator(Protocol):
    """What the views of the entries ask the window to show."""

    def select_entry(self, entry_id: str) -> None: ...
    def go_back_to_settings(self, entry_id: str) -> None: ...
    def show_preferences(self, tab: str | None = None) -> None: ...
    def set_api_key(self, env_key: EnvKeys) -> None: ...
    def show_status(self, message: str, is_error: bool = False) -> None: ...


@dataclass(frozen=True)
class EntryActions:
    """Everything the views of the entries can do, grouped by who does it."""

    files: EntryFiles
    transcript: TranscriptEditor
    jobs: JobControls
    prompts: EntryPrompts
    window: Navigator
