from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class Chapter:
    """A part of the transcription about one topic, from the given second on."""

    start: float
    title: str


@dataclass(frozen=True)
class TranscriptSummary:
    """A summary of a transcription, generated by a language model."""

    summary: str
    key_points: tuple[str, ...] = ()
    # Only available if the transcription has timestamps
    chapters: tuple[Chapter, ...] = ()
    # The model that generated it, e.g. "gpt-5.4-mini"
    model: str = ""
    created_at: str = ""
    # Whether the transcription was too long and only its beginning was summarized
    is_partial: bool = field(default=False)

    def to_dict(self) -> dict[str, Any]:
        return {
            "summary": self.summary,
            "key_points": list(self.key_points),
            "chapters": [[chapter.start, chapter.title] for chapter in self.chapters],
            "model": self.model,
            "created_at": self.created_at,
            "is_partial": self.is_partial,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "TranscriptSummary | None":
        """:return: The summary, or None if there is none (an empty dict)."""
        if not data.get("summary"):
            return None

        return cls(
            summary=str(data["summary"]),
            key_points=tuple(str(point) for point in data.get("key_points", [])),
            chapters=tuple(
                Chapter(float(start), str(title))
                for start, title in data.get("chapters", [])
            ),
            model=str(data.get("model", "")),
            created_at=str(data.get("created_at", "")),
            is_partial=bool(data.get("is_partial", False)),
        )
