AUDIO_LANGUAGES = {
    "af": "Afrikaans",
    "am": "አማርኛ",
    "ar": "العربية",
    "ar_AE": "(العربية (الإمارات",
    "ar_BH": "(العربية (البحرين",
    "ar_DZ": "(العربية (الجزائر",
    "ar_EG": "(العربية (مصر",
    "ar_IL": "(العربية (إسرائيل",
    "ar_JO": "(العربية (الأردن",
    "ar_KW": "(العربية (الكويت",
    "ar_LB": "(العربية (لبنان",
    "ar_MA": "(العربية (المغرب",
    "ar_OM": "(العربية (عُمان",
    "ar_PS": "(العربية (فلسطين",
    "ar_QA": "(العربية (قطر",
    "ar_SA": "(العربية (السعودية",
    "ar_TN": "(العربية (تونس",
    "az": "Azərbaycan",
    "be": "беларуская",
    "bg": "Български",
    "bn": "বাংলা",
    "bn_BD": "বাংলা (বাংলাদেশ)",
    "bn_IN": "বাংলা (ভারত)",
    "ca": "Català",
    "cs": "Čeština",
    "da": "Dansk",
    "de": "Deutsch",
    "de_CH": "Schweizer Hochdeutsch",
    "el": "Ελληνικά",
    "en": "English",
    "en_US": "English (United States)",
    "en_AU": "English (Australia)",
    "en_CA": "English (Canada)",
    "en_GB": "English (United Kingdom)",
    "en_GH": "English (Ghana)",
    "en_IE": "English (Ireland)",
    "en_IN": "English (India)",
    "en_KE": "English (Kenya)",
    "en_NZ": "English (New Zealand)",
    "en_NG": "English (Nigeria)",
    "en_PH": "English (Philippines)",
    "en_TZ": "English (Tanzania)",
    "en_ZA": "English (South Africa)",
    "es": "Español",
    "es_419": "Español (Latinoamérica)",
    "es_AR": "Español (Argentina)",
    "es_BO": "Español (Bolivia)",
    "es_CL": "Español (Chile)",
    "es_CO": "Español (Colombia)",
    "es_CR": "Español (Costa Rica)",
    "es_DO": "Español (República Dominicana)",
    "es_EC": "Español (Ecuador)",
    "es_ES": "Español (España)",
    "es_GT": "Español (Guatemala)",
    "es_HN": "Español (Honduras)",
    "es_MX": "Español (México)",
    "es_NI": "Español (Nicaragua)",
    "es_PA": "Español (Panamá)",
    "es_PE": "Español (Perú)",
    "es_PR": "Español (Puerto Rico)",
    "es_PY": "Español (Paraguay)",
    "es_SV": "Español (El Salvador)",
    "es_US": "Español (Estados Unidos)",
    "es_UY": "Español (Uruguay)",
    "es_VE": "Español (Venezuela)",
    "et": "Eesti",
    "eu": "Euskara",
    "fa": "فارسی",
    "fi": "Suomi",
    "fil": "Filipino",
    "fr": "Français",
    "fr_CA": "Français (Canada)",
    "gl": "Galego",
    "gu": "ગુજરાતી",
    "hi": "हिन्दी",
    "hr": "Hrvatski",
    "hu": "Magyar",
    "hy": "հայերեն",
    "id": "Bahasa Indonesia",
    "is": "Íslenska",
    "it": "Italiano",
    "it_CH": "Italiano (Svizzera)",
    "it_IT": "Italiano (Italia)",
    "iw": "עברית",
    "ja": "日本語",
    "jv": "Basa Jawa",
    "ka": "ქართულად",
    "kk": "Қазақ",
    "km": "ខ្មែរ",
    "kn": "ಕನ್ನಡ",
    "ko": "한국어",
    "lo": "ລາວ",
    "lt": "Lietuvių",
    "lv": "Latviešu",
    "ml": "മലയാളം",
    "mn": "Монгол",
    "mr": "मराठी",
    "ms": "Bahasa Melayu",
    "mt": "Malti",
    "ne": "नेपाली",
    "nl": "Nederlands",
    "nn": "Norsk (Nynorsk)",
    "no": "Norsk (Bokmål)",
    "pa": "ਪੰਜਾਬੀ",
    "pl": "Polski",
    "pt_BR": "Português (Brasil)",
    "pt_PT": "Português (Portugal)",
    "pt": "Português",
    "ro": "Română",
    "ru": "Русский",
    "si": "සිංහල",
    "sk": "Slovenčina",
    "sl": "Slovenščina",
    "sr": "Српски",
    "su": "Basa Sunda",
    "sv": "Svenska",
    "sw": "Kiswahili",
    "sw_KE": "Kiswahili (Kenya)",
    "sw_TZ": "Kiswahili (Tanzania)",
    "ta": "தமிழ்",
    "ta_IN": "தமிழ் (இந்தியா)",
    "ta_LK": "தமிழ் (இலங்கை)",
    "ta_MY": "தமிழ் (மலேஷியா)",
    "ta_SG": "தமிழ் (சிங்கப்பூர்)",
    "te": "తెలుగు",
    "th": "ไทย",
    "tr": "Türkçe",
    "uk": "Українська",
    "ur": "اردو",
    "ur_IN": "(اردو (بھارت",
    "ur_PK": "(اردو (پاکستان",
    "vi": "Tiếng Việt",
    "zh_CN": "中文（中国）",
    "zh_HK": "中文（香港）",
    "zh_TW": "中文（台灣）",
    "zu": "Isizulu",
}

APP_LANGUAGES = {
    "en": "English",
    "es": "Español"
}

FILE = "file"
MIC = "mic"

AUDIO_FILE_EXTENSIONS = {
    "mp3": [".mp3", ".mpeg"],
    "wav": [".wav", "wma"],
    "ogg": [".ogg", ".oga", ".opus"],
}

# fmt: off
VIDEO_FILE_EXTENSIONS = [
    ".mp4", ".m4a", ".m4v", ".f4v", ".f4a", ".m4b", ".m4r", ".f4b", ".mov",  # MP4
    ".avi",  # AVI
    ".webm",  # WebM
    ".flv",  # FLV
    ".mkv",  # MKV
    ".3gp", ".3gp2", ".3g2", ".3gpp", ".3gpp2",  # 3GP
    ".ogv", ".ogx",  # OGG
    ".wmv", ".asf"  # AIFF / ASF
]
